export const COUNTRY_CODES = [
  { name: "Afghanistan", alpha2Code: "AF", alpha3Code: "AFG", numeric: 4 },
  { name: "Albania", alpha2Code: "AL", alpha3Code: "ALB", numeric: 8 },
  { name: "Algeria", alpha2Code: "DZ", alpha3Code: "DZA", numeric: 12 },
  { name: "American Samoa", alpha2Code: "AS", alpha3Code: "ASM", numeric: 16 },
  { name: "Andorra", alpha2Code: "AD", alpha3Code: "AND", numeric: 20 },
  { name: "Angola", alpha2Code: "AO", alpha3Code: "AGO", numeric: 24 },
  { name: "Anguilla", alpha2Code: "AI", alpha3Code: "AIA", numeric: 660 },
  { name: "Antarctica", alpha2Code: "AQ", alpha3Code: "ATA", numeric: 10 },
  {
    name: "Antigua and Barbuda",
    alpha2Code: "AG",
    alpha3Code: "ATG",
    numeric: 28,
  },
  { name: "Argentina", alpha2Code: "AR", alpha3Code: "ARG", numeric: 32 },
  { name: "Armenia", alpha2Code: "AM", alpha3Code: "ARM", numeric: 51 },
  { name: "Aruba", alpha2Code: "AW", alpha3Code: "ABW", numeric: 533 },
  { name: "Australia", alpha2Code: "AU", alpha3Code: "AUS", numeric: 36 },
  { name: "Austria", alpha2Code: "AT", alpha3Code: "AUT", numeric: 40 },
  { name: "Azerbaijan", alpha2Code: "AZ", alpha3Code: "AZE", numeric: 31 },
  { name: "Bahamas (the)", alpha2Code: "BS", alpha3Code: "BHS", numeric: 44 },
  { name: "Bahrain", alpha2Code: "BH", alpha3Code: "BHR", numeric: 48 },
  { name: "Bangladesh", alpha2Code: "BD", alpha3Code: "BGD", numeric: 50 },
  { name: "Barbados", alpha2Code: "BB", alpha3Code: "BRB", numeric: 52 },
  { name: "Belarus", alpha2Code: "BY", alpha3Code: "BLR", numeric: 112 },
  { name: "Belgium", alpha2Code: "BE", alpha3Code: "BEL", numeric: 56 },
  { name: "Belize", alpha2Code: "BZ", alpha3Code: "BLZ", numeric: 84 },
  { name: "Benin", alpha2Code: "BJ", alpha3Code: "BEN", numeric: 204 },
  { name: "Bermuda", alpha2Code: "BM", alpha3Code: "BMU", numeric: 60 },
  { name: "Bhutan", alpha2Code: "BT", alpha3Code: "BTN", numeric: 64 },
  {
    name: "Bolivia (Plurinational State of)",
    alpha2Code: "BO",
    alpha3Code: "BOL",
    numeric: 68,
  },
  {
    name: "Bonaire, Sint Eustatius and Saba",
    alpha2Code: "BQ",
    alpha3Code: "BES",
    numeric: 535,
  },
  {
    name: "Bosnia and Herzegovina",
    alpha2Code: "BA",
    alpha3Code: "BIH",
    numeric: 70,
  },
  { name: "Botswana", alpha2Code: "BW", alpha3Code: "BWA", numeric: 72 },
  { name: "Bouvet Island", alpha2Code: "BV", alpha3Code: "BVT", numeric: 74 },
  { name: "Brazil", alpha2Code: "BR", alpha3Code: "BRA", numeric: 76 },
  {
    name: "British Indian Ocean Territory (the)",
    alpha2Code: "IO",
    alpha3Code: "IOT",
    numeric: 86,
  },
  {
    name: "Brunei Darussalam",
    alpha2Code: "BN",
    alpha3Code: "BRN",
    numeric: 96,
  },
  { name: "Bulgaria", alpha2Code: "BG", alpha3Code: "BGR", numeric: 100 },
  { name: "Burkina Faso", alpha2Code: "BF", alpha3Code: "BFA", numeric: 854 },
  { name: "Burundi", alpha2Code: "BI", alpha3Code: "BDI", numeric: 108 },
  { name: "Cabo Verde", alpha2Code: "CV", alpha3Code: "CPV", numeric: 132 },
  { name: "Cambodia", alpha2Code: "KH", alpha3Code: "KHM", numeric: 116 },
  { name: "Cameroon", alpha2Code: "CM", alpha3Code: "CMR", numeric: 120 },
  { name: "Canada", alpha2Code: "CA", alpha3Code: "CAN", numeric: 124 },
  {
    name: "Cayman Islands (the)",
    alpha2Code: "KY",
    alpha3Code: "CYM",
    numeric: 136,
  },
  {
    name: "Central African Republic (the)",
    alpha2Code: "CF",
    alpha3Code: "CAF",
    numeric: 140,
  },
  { name: "Chad", alpha2Code: "TD", alpha3Code: "TCD", numeric: 148 },
  { name: "Chile", alpha2Code: "CL", alpha3Code: "CHL", numeric: 152 },
  { name: "China", alpha2Code: "CN", alpha3Code: "CHN", numeric: 156 },
  {
    name: "Christmas Island",
    alpha2Code: "CX",
    alpha3Code: "CXR",
    numeric: 162,
  },
  {
    name: "Cocos (Keeling) Islands (the)",
    alpha2Code: "CC",
    alpha3Code: "CCK",
    numeric: 166,
  },
  { name: "Colombia", alpha2Code: "CO", alpha3Code: "COL", numeric: 170 },
  { name: "Comoros (the)", alpha2Code: "KM", alpha3Code: "COM", numeric: 174 },
  {
    name: "Congo (the Democratic Republic of the)",
    alpha2Code: "CD",
    alpha3Code: "COD",
    numeric: 180,
  },
  { name: "Congo (the)", alpha2Code: "CG", alpha3Code: "COG", numeric: 178 },
  {
    name: "Cook Islands (the)",
    alpha2Code: "CK",
    alpha3Code: "COK",
    numeric: 184,
  },
  { name: "Costa Rica", alpha2Code: "CR", alpha3Code: "CRI", numeric: 188 },
  { name: "Croatia", alpha2Code: "HR", alpha3Code: "HRV", numeric: 191 },
  { name: "Cuba", alpha2Code: "CU", alpha3Code: "CUB", numeric: 192 },
  { name: "Curaçao", alpha2Code: "CW", alpha3Code: "CUW", numeric: 531 },
  { name: "Cyprus", alpha2Code: "CY", alpha3Code: "CYP", numeric: 196 },
  { name: "Czechia", alpha2Code: "CZ", alpha3Code: "CZE", numeric: 203 },
  { name: "Côte d'Ivoire", alpha2Code: "CI", alpha3Code: "CIV", numeric: 384 },
  { name: "Denmark", alpha2Code: "DK", alpha3Code: "DNK", numeric: 208 },
  { name: "Djibouti", alpha2Code: "DJ", alpha3Code: "DJI", numeric: 262 },
  { name: "Dominica", alpha2Code: "DM", alpha3Code: "DMA", numeric: 212 },
  {
    name: "Dominican Republic (the)",
    alpha2Code: "DO",
    alpha3Code: "DOM",
    numeric: 214,
  },
  { name: "Ecuador", alpha2Code: "EC", alpha3Code: "ECU", numeric: 218 },
  { name: "Egypt", alpha2Code: "EG", alpha3Code: "EGY", numeric: 818 },
  { name: "El Salvador", alpha2Code: "SV", alpha3Code: "SLV", numeric: 222 },
  {
    name: "Equatorial Guinea",
    alpha2Code: "GQ",
    alpha3Code: "GNQ",
    numeric: 226,
  },
  { name: "Eritrea", alpha2Code: "ER", alpha3Code: "ERI", numeric: 232 },
  { name: "Estonia", alpha2Code: "EE", alpha3Code: "EST", numeric: 233 },
  { name: "Eswatini", alpha2Code: "SZ", alpha3Code: "SWZ", numeric: 748 },
  { name: "Ethiopia", alpha2Code: "ET", alpha3Code: "ETH", numeric: 231 },
  {
    name: "Falkland Islands (the) [Malvinas]",
    alpha2Code: "FK",
    alpha3Code: "FLK",
    numeric: 238,
  },
  {
    name: "Faroe Islands (the)",
    alpha2Code: "FO",
    alpha3Code: "FRO",
    numeric: 234,
  },
  { name: "Fiji", alpha2Code: "FJ", alpha3Code: "FJI", numeric: 242 },
  { name: "Finland", alpha2Code: "FI", alpha3Code: "FIN", numeric: 246 },
  { name: "France", alpha2Code: "FR", alpha3Code: "FRA", numeric: 250 },
  { name: "French Guiana", alpha2Code: "GF", alpha3Code: "GUF", numeric: 254 },
  {
    name: "French Polynesia",
    alpha2Code: "PF",
    alpha3Code: "PYF",
    numeric: 258,
  },
  {
    name: "French Southern Territories (the)",
    alpha2Code: "TF",
    alpha3Code: "ATF",
    numeric: 260,
  },
  { name: "Gabon", alpha2Code: "GA", alpha3Code: "GAB", numeric: 266 },
  { name: "Gambia (the)", alpha2Code: "GM", alpha3Code: "GMB", numeric: 270 },
  { name: "Georgia", alpha2Code: "GE", alpha3Code: "GEO", numeric: 268 },
  { name: "Germany", alpha2Code: "DE", alpha3Code: "DEU", numeric: 276 },
  { name: "Ghana", alpha2Code: "GH", alpha3Code: "GHA", numeric: 288 },
  { name: "Gibraltar", alpha2Code: "GI", alpha3Code: "GIB", numeric: 292 },
  { name: "Greece", alpha2Code: "GR", alpha3Code: "GRC", numeric: 300 },
  { name: "Greenland", alpha2Code: "GL", alpha3Code: "GRL", numeric: 304 },
  { name: "Grenada", alpha2Code: "GD", alpha3Code: "GRD", numeric: 308 },
  { name: "Guadeloupe", alpha2Code: "GP", alpha3Code: "GLP", numeric: 312 },
  { name: "Guam", alpha2Code: "GU", alpha3Code: "GUM", numeric: 316 },
  { name: "Guatemala", alpha2Code: "GT", alpha3Code: "GTM", numeric: 320 },
  { name: "Guernsey", alpha2Code: "GG", alpha3Code: "GGY", numeric: 831 },
  { name: "Guinea", alpha2Code: "GN", alpha3Code: "GIN", numeric: 324 },
  { name: "Guinea-Bissau", alpha2Code: "GW", alpha3Code: "GNB", numeric: 624 },
  { name: "Guyana", alpha2Code: "GY", alpha3Code: "GUY", numeric: 328 },
  { name: "Haiti", alpha2Code: "HT", alpha3Code: "HTI", numeric: 332 },
  {
    name: "Heard Island and McDonald Islands",
    alpha2Code: "HM",
    alpha3Code: "HMD",
    numeric: 334,
  },
  { name: "Holy See (the)", alpha2Code: "VA", alpha3Code: "VAT", numeric: 336 },
  { name: "Honduras", alpha2Code: "HN", alpha3Code: "HND", numeric: 340 },
  { name: "Hong Kong", alpha2Code: "HK", alpha3Code: "HKG", numeric: 344 },
  { name: "Hungary", alpha2Code: "HU", alpha3Code: "HUN", numeric: 348 },
  { name: "Iceland", alpha2Code: "IS", alpha3Code: "ISL", numeric: 352 },
  { name: "India", alpha2Code: "IN", alpha3Code: "IND", numeric: 356 },
  { name: "Indonesia", alpha2Code: "ID", alpha3Code: "IDN", numeric: 360 },
  {
    name: "Iran (Islamic Republic of)",
    alpha2Code: "IR",
    alpha3Code: "IRN",
    numeric: 364,
  },
  { name: "Iraq", alpha2Code: "IQ", alpha3Code: "IRQ", numeric: 368 },
  { name: "Ireland", alpha2Code: "IE", alpha3Code: "IRL", numeric: 372 },
  { name: "Isle of Man", alpha2Code: "IM", alpha3Code: "IMN", numeric: 833 },
  { name: "Israel", alpha2Code: "IL", alpha3Code: "ISR", numeric: 376 },
  { name: "Italy", alpha2Code: "IT", alpha3Code: "ITA", numeric: 380 },
  { name: "Jamaica", alpha2Code: "JM", alpha3Code: "JAM", numeric: 388 },
  { name: "Japan", alpha2Code: "JP", alpha3Code: "JPN", numeric: 392 },
  { name: "Jersey", alpha2Code: "JE", alpha3Code: "JEY", numeric: 832 },
  { name: "Jordan", alpha2Code: "JO", alpha3Code: "JOR", numeric: 400 },
  { name: "Kazakhstan", alpha2Code: "KZ", alpha3Code: "KAZ", numeric: 398 },
  { name: "Kenya", alpha2Code: "KE", alpha3Code: "KEN", numeric: 404 },
  { name: "Kiribati", alpha2Code: "KI", alpha3Code: "KIR", numeric: 296 },
  {
    name: "Korea (the Democratic People's Republic of)",
    alpha2Code: "KP",
    alpha3Code: "PRK",
    numeric: 408,
  },
  {
    name: "Korea (the Republic of)",
    alpha2Code: "KR",
    alpha3Code: "KOR",
    numeric: 410,
  },
  { name: "Kuwait", alpha2Code: "KW", alpha3Code: "KWT", numeric: 414 },
  { name: "Kyrgyzstan", alpha2Code: "KG", alpha3Code: "KGZ", numeric: 417 },
  {
    name: "Lao People's Democratic Republic (the)",
    alpha2Code: "LA",
    alpha3Code: "LAO",
    numeric: 418,
  },
  { name: "Latvia", alpha2Code: "LV", alpha3Code: "LVA", numeric: 428 },
  { name: "Lebanon", alpha2Code: "LB", alpha3Code: "LBN", numeric: 422 },
  { name: "Lesotho", alpha2Code: "LS", alpha3Code: "LSO", numeric: 426 },
  { name: "Liberia", alpha2Code: "LR", alpha3Code: "LBR", numeric: 430 },
  { name: "Libya", alpha2Code: "LY", alpha3Code: "LBY", numeric: 434 },
  { name: "Liechtenstein", alpha2Code: "LI", alpha3Code: "LIE", numeric: 438 },
  { name: "Lithuania", alpha2Code: "LT", alpha3Code: "LTU", numeric: 440 },
  { name: "Luxembourg", alpha2Code: "LU", alpha3Code: "LUX", numeric: 442 },
  { name: "Macao", alpha2Code: "MO", alpha3Code: "MAC", numeric: 446 },
  { name: "Madagascar", alpha2Code: "MG", alpha3Code: "MDG", numeric: 450 },
  { name: "Malawi", alpha2Code: "MW", alpha3Code: "MWI", numeric: 454 },
  { name: "Malaysia", alpha2Code: "MY", alpha3Code: "MYS", numeric: 458 },
  { name: "Maldives", alpha2Code: "MV", alpha3Code: "MDV", numeric: 462 },
  { name: "Mali", alpha2Code: "ML", alpha3Code: "MLI", numeric: 466 },
  { name: "Malta", alpha2Code: "MT", alpha3Code: "MLT", numeric: 470 },
  {
    name: "Marshall Islands (the)",
    alpha2Code: "MH",
    alpha3Code: "MHL",
    numeric: 584,
  },
  { name: "Martinique", alpha2Code: "MQ", alpha3Code: "MTQ", numeric: 474 },
  { name: "Mauritania", alpha2Code: "MR", alpha3Code: "MRT", numeric: 478 },
  { name: "Mauritius", alpha2Code: "MU", alpha3Code: "MUS", numeric: 480 },
  { name: "Mayotte", alpha2Code: "YT", alpha3Code: "MYT", numeric: 175 },
  { name: "Mexico", alpha2Code: "MX", alpha3Code: "MEX", numeric: 484 },
  {
    name: "Micronesia (Federated States of)",
    alpha2Code: "FM",
    alpha3Code: "FSM",
    numeric: 583,
  },
  {
    name: "Moldova (the Republic of)",
    alpha2Code: "MD",
    alpha3Code: "MDA",
    numeric: 498,
  },
  { name: "Monaco", alpha2Code: "MC", alpha3Code: "MCO", numeric: 492 },
  { name: "Mongolia", alpha2Code: "MN", alpha3Code: "MNG", numeric: 496 },
  { name: "Montenegro", alpha2Code: "ME", alpha3Code: "MNE", numeric: 499 },
  { name: "Montserrat", alpha2Code: "MS", alpha3Code: "MSR", numeric: 500 },
  { name: "Morocco", alpha2Code: "MA", alpha3Code: "MAR", numeric: 504 },
  { name: "Mozambique", alpha2Code: "MZ", alpha3Code: "MOZ", numeric: 508 },
  { name: "Myanmar", alpha2Code: "MM", alpha3Code: "MMR", numeric: 104 },
  { name: "Namibia", alpha2Code: "NA", alpha3Code: "NAM", numeric: 516 },
  { name: "Nauru", alpha2Code: "NR", alpha3Code: "NRU", numeric: 520 },
  { name: "Nepal", alpha2Code: "NP", alpha3Code: "NPL", numeric: 524 },
  {
    name: "Netherlands (the)",
    alpha2Code: "NL",
    alpha3Code: "NLD",
    numeric: 528,
  },
  { name: "New Caledonia", alpha2Code: "NC", alpha3Code: "NCL", numeric: 540 },
  { name: "New Zealand", alpha2Code: "NZ", alpha3Code: "NZL", numeric: 554 },
  { name: "Nicaragua", alpha2Code: "NI", alpha3Code: "NIC", numeric: 558 },
  { name: "Niger (the)", alpha2Code: "NE", alpha3Code: "NER", numeric: 562 },
  { name: "Nigeria", alpha2Code: "NG", alpha3Code: "NGA", numeric: 566 },
  { name: "Niue", alpha2Code: "NU", alpha3Code: "NIU", numeric: 570 },
  { name: "Norfolk Island", alpha2Code: "NF", alpha3Code: "NFK", numeric: 574 },
  {
    name: "Northern Mariana Islands (the)",
    alpha2Code: "MP",
    alpha3Code: "MNP",
    numeric: 580,
  },
  { name: "Norway", alpha2Code: "NO", alpha3Code: "NOR", numeric: 578 },
  { name: "Oman", alpha2Code: "OM", alpha3Code: "OMN", numeric: 512 },
  { name: "Pakistan", alpha2Code: "PK", alpha3Code: "PAK", numeric: 586 },
  { name: "Palau", alpha2Code: "PW", alpha3Code: "PLW", numeric: 585 },
  {
    name: "Palestine, State of",
    alpha2Code: "PS",
    alpha3Code: "PSE",
    numeric: 275,
  },
  { name: "Panama", alpha2Code: "PA", alpha3Code: "PAN", numeric: 591 },
  {
    name: "Papua New Guinea",
    alpha2Code: "PG",
    alpha3Code: "PNG",
    numeric: 598,
  },
  { name: "Paraguay", alpha2Code: "PY", alpha3Code: "PRY", numeric: 600 },
  { name: "Peru", alpha2Code: "PE", alpha3Code: "PER", numeric: 604 },
  {
    name: "Philippines (the)",
    alpha2Code: "PH",
    alpha3Code: "PHL",
    numeric: 608,
  },
  { name: "Pitcairn", alpha2Code: "PN", alpha3Code: "PCN", numeric: 612 },
  { name: "Poland", alpha2Code: "PL", alpha3Code: "POL", numeric: 616 },
  { name: "Portugal", alpha2Code: "PT", alpha3Code: "PRT", numeric: 620 },
  { name: "Puerto Rico", alpha2Code: "PR", alpha3Code: "PRI", numeric: 630 },
  { name: "Qatar", alpha2Code: "QA", alpha3Code: "QAT", numeric: 634 },
  {
    name: "Republic of North Macedonia",
    alpha2Code: "MK",
    alpha3Code: "MKD",
    numeric: 807,
  },
  { name: "Romania", alpha2Code: "RO", alpha3Code: "ROU", numeric: 642 },
  {
    name: "Russian Federation (the)",
    alpha2Code: "RU",
    alpha3Code: "RUS",
    numeric: 643,
  },
  { name: "Rwanda", alpha2Code: "RW", alpha3Code: "RWA", numeric: 646 },
  { name: "Réunion", alpha2Code: "RE", alpha3Code: "REU", numeric: 638 },
  {
    name: "Saint Barthélemy",
    alpha2Code: "BL",
    alpha3Code: "BLM",
    numeric: 652,
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    alpha2Code: "SH",
    alpha3Code: "SHN",
    numeric: 654,
  },
  {
    name: "Saint Kitts and Nevis",
    alpha2Code: "KN",
    alpha3Code: "KNA",
    numeric: 659,
  },
  { name: "Saint Lucia", alpha2Code: "LC", alpha3Code: "LCA", numeric: 662 },
  {
    name: "Saint Martin (French part)",
    alpha2Code: "MF",
    alpha3Code: "MAF",
    numeric: 663,
  },
  {
    name: "Saint Pierre and Miquelon",
    alpha2Code: "PM",
    alpha3Code: "SPM",
    numeric: 666,
  },
  {
    name: "Saint Vincent and the Grenadines",
    alpha2Code: "VC",
    alpha3Code: "VCT",
    numeric: 670,
  },
  { name: "Samoa", alpha2Code: "WS", alpha3Code: "WSM", numeric: 882 },
  { name: "San Marino", alpha2Code: "SM", alpha3Code: "SMR", numeric: 674 },
  {
    name: "Sao Tome and Principe",
    alpha2Code: "ST",
    alpha3Code: "STP",
    numeric: 678,
  },
  { name: "Saudi Arabia", alpha2Code: "SA", alpha3Code: "SAU", numeric: 682 },
  { name: "Senegal", alpha2Code: "SN", alpha3Code: "SEN", numeric: 686 },
  { name: "Serbia", alpha2Code: "RS", alpha3Code: "SRB", numeric: 688 },
  { name: "Seychelles", alpha2Code: "SC", alpha3Code: "SYC", numeric: 690 },
  { name: "Sierra Leone", alpha2Code: "SL", alpha3Code: "SLE", numeric: 694 },
  { name: "Singapore", alpha2Code: "SG", alpha3Code: "SGP", numeric: 702 },
  {
    name: "Sint Maarten (Dutch part)",
    alpha2Code: "SX",
    alpha3Code: "SXM",
    numeric: 534,
  },
  { name: "Slovakia", alpha2Code: "SK", alpha3Code: "SVK", numeric: 703 },
  { name: "Slovenia", alpha2Code: "SI", alpha3Code: "SVN", numeric: 705 },
  { name: "Solomon Islands", alpha2Code: "SB", alpha3Code: "SLB", numeric: 90 },
  { name: "Somalia", alpha2Code: "SO", alpha3Code: "SOM", numeric: 706 },
  { name: "South Africa", alpha2Code: "ZA", alpha3Code: "ZAF", numeric: 710 },
  {
    name: "South Georgia and the South Sandwich Islands",
    alpha2Code: "GS",
    alpha3Code: "SGS",
    numeric: 239,
  },
  { name: "South Sudan", alpha2Code: "SS", alpha3Code: "SSD", numeric: 728 },
  { name: "Spain", alpha2Code: "ES", alpha3Code: "ESP", numeric: 724 },
  { name: "Sri Lanka", alpha2Code: "LK", alpha3Code: "LKA", numeric: 144 },
  { name: "Sudan (the)", alpha2Code: "SD", alpha3Code: "SDN", numeric: 729 },
  { name: "Suriname", alpha2Code: "SR", alpha3Code: "SUR", numeric: 740 },
  {
    name: "Svalbard and Jan Mayen",
    alpha2Code: "SJ",
    alpha3Code: "SJM",
    numeric: 744,
  },
  { name: "Sweden", alpha2Code: "SE", alpha3Code: "SWE", numeric: 752 },
  { name: "Switzerland", alpha2Code: "CH", alpha3Code: "CHE", numeric: 756 },
  {
    name: "Syrian Arab Republic",
    alpha2Code: "SY",
    alpha3Code: "SYR",
    numeric: 760,
  },
  {
    name: "Taiwan (Province of China)",
    alpha2Code: "TW",
    alpha3Code: "TWN",
    numeric: 158,
  },
  { name: "Tajikistan", alpha2Code: "TJ", alpha3Code: "TJK", numeric: 762 },
  {
    name: "Tanzania, United Republic of",
    alpha2Code: "TZ",
    alpha3Code: "TZA",
    numeric: 834,
  },
  { name: "Thailand", alpha2Code: "TH", alpha3Code: "THA", numeric: 764 },
  { name: "Timor-Leste", alpha2Code: "TL", alpha3Code: "TLS", numeric: 626 },
  { name: "Togo", alpha2Code: "TG", alpha3Code: "TGO", numeric: 768 },
  { name: "Tokelau", alpha2Code: "TK", alpha3Code: "TKL", numeric: 772 },
  { name: "Tonga", alpha2Code: "TO", alpha3Code: "TON", numeric: 776 },
  {
    name: "Trinidad and Tobago",
    alpha2Code: "TT",
    alpha3Code: "TTO",
    numeric: 780,
  },
  { name: "Tunisia", alpha2Code: "TN", alpha3Code: "TUN", numeric: 788 },
  { name: "Turkey", alpha2Code: "TR", alpha3Code: "TUR", numeric: 792 },
  { name: "Turkmenistan", alpha2Code: "TM", alpha3Code: "TKM", numeric: 795 },
  {
    name: "Turks and Caicos Islands (the)",
    alpha2Code: "TC",
    alpha3Code: "TCA",
    numeric: 796,
  },
  { name: "Tuvalu", alpha2Code: "TV", alpha3Code: "TUV", numeric: 798 },
  { name: "Uganda", alpha2Code: "UG", alpha3Code: "UGA", numeric: 800 },
  { name: "Ukraine", alpha2Code: "UA", alpha3Code: "UKR", numeric: 804 },
  {
    name: "United Arab Emirates (the)",
    alpha2Code: "AE",
    alpha3Code: "ARE",
    numeric: 784,
  },
  {
    name: "United Kingdom of Great Britain and Northern Ireland (the)",
    alpha2Code: "GB",
    alpha3Code: "GBR",
    numeric: 826,
  },
  {
    name: "United States Minor Outlying Islands (the)",
    alpha2Code: "UM",
    alpha3Code: "UMI",
    numeric: 581,
  },
  {
    name: "United States of America (the)",
    alpha2Code: "US",
    alpha3Code: "USA",
    numeric: 840,
  },
  { name: "Uruguay", alpha2Code: "UY", alpha3Code: "URY", numeric: 858 },
  { name: "Uzbekistan", alpha2Code: "UZ", alpha3Code: "UZB", numeric: 860 },
  { name: "Vanuatu", alpha2Code: "VU", alpha3Code: "VUT", numeric: 548 },
  {
    name: "Venezuela (Bolivarian Republic of)",
    alpha2Code: "VE",
    alpha3Code: "VEN",
    numeric: 862,
  },
  { name: "Viet Nam", alpha2Code: "VN", alpha3Code: "VNM", numeric: 704 },
  {
    name: "Virgin Islands (British)",
    alpha2Code: "VG",
    alpha3Code: "VGB",
    numeric: 92,
  },
  {
    name: "Virgin Islands (U.S.)",
    alpha2Code: "VI",
    alpha3Code: "VIR",
    numeric: 850,
  },
  {
    name: "Wallis and Futuna",
    alpha2Code: "WF",
    alpha3Code: "WLF",
    numeric: 876,
  },
  { name: "Western Sahara", alpha2Code: "EH", alpha3Code: "ESH", numeric: 732 },
  { name: "Yemen", alpha2Code: "YE", alpha3Code: "YEM", numeric: 887 },
  { name: "Zambia", alpha2Code: "ZM", alpha3Code: "ZMB", numeric: 894 },
  { name: "Zimbabwe", alpha2Code: "ZW", alpha3Code: "ZWE", numeric: 716 },
  { name: "Åland Islands", alpha2Code: "AX", alpha3Code: "ALA", numeric: 248 },
];
